name: node test

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: to make a post req
    steps:
      # To use this repository's private action
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: send a post request 
        uses: ./ # Uses an action in the root directory
        
    
 
